### ISSUE TITLE
Possibility to save hash data without sharing it to the public

### ISSUE THREAD

**Issue by dutchhappy** [airdcpp/airdcpp-windows#105]
### Prerequisites

- [X] This is not a [support issue or a question](https://github.com/airdcpp/airdcpp-windows/discussions)
- [X] I performed a [cursory search of the issue tracker](https://github.com/airdcpp/airdcpp-windows/issues) to avoid opening a duplicate issue

### Is your proposal related to a problem?

no

### Describe the solution you would like

possibility to save hash data without sharing it to the public

**Comment by maksis** [comment]
I don't understand that what's being requested

**Comment by maldond** [comment]
My bet is he can achieve what he asks by just hashing/downloading files to an alternative Share Profile not shared to any hub, that way whenever he searches or browses, results that match that "hidden" secondary Share Profile will appear as owned. At least for ADC hubs not sure about NMDC.

**Comment by maksis** [comment]
It's not protocol-specific since the profile isn't shared anywhere, so no changes are needed I assume
