### ISSUE TITLE
Search Results by popular name first

### ISSUE THREAD

**Issue by leaderdog** [airdcpp/airdcpp-windows#113]
### Prerequisites

- [X] This is not a [support issue or a question](https://github.com/airdcpp/airdcpp-windows/discussions)
- [X] I performed a [cursory search of the issue tracker](https://github.com/airdcpp/airdcpp-windows/issues) to avoid opening a duplicate issue

### Is your proposal related to a problem?

Search results will have random names when looking for the most common, or proper release name it will be under someone else's random naming scheme.

In the included image you will see the release name is the dominant naming format, but it's under the goofy naming scheme or one person.  Which means the automatic downloading isn't a great idea as your files now are out of order, or you have to manually rename each file downloaded.

### Describe the solution you would like

Ideally the search result should be the most popular which, in this case, would be the original file name.

### Screenshot(s)

![searchresults](https://github.com/airdcpp/airdcpp-windows/assets/39628596/87284b92-7699-4eb6-bae4-b4366ca084e7)

### Additional information

Thanks for reading. :)

**Comment by maksis** [comment]
Yeah that would be a reasonable thing to do

**Comment by maksis** [comment]
This will be available in the next release
