### ISSUE TITLE
🐛 [Bug]: c0000006

### ISSUE THREAD

**Issue by hotjo68** [airdcpp/airdcpp-windows#114]
### Prerequisites

- [X] This is not a [support issue or a question](https://github.com/airdcpp/airdcpp-windows/discussions)
- [X] I performed a [cursory search of the issue tracker](https://github.com/airdcpp/airdcpp-windows/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of AirDC++

### Describe the issue

Start the client, the error come at the same time as I  start it.

### Expected behavior

Start the client, the error come at the same time as I  start it.

### Actual behavior

Start the client, the error come at the same time as I  start it.

### Steps to reproduce the behavior if needed

Start the client, the error come at the same time as I  start it.

### Crash log

```shell
Code: c0000006 ( Page error )
Version: AirDC++ 4.21 x64
Build: 4688
Major: 6
Minor: 2
Build: 9200
SP: 0
Type: 1
Time: 2024-03-24 14:10:00
TTH: XVD7Y4Y3ZK7WZVKBIITFBKENJZ4XJD7NOWVPHVY

D:\a\_work\1\s\src\vctools\crt\vcruntime\src\string\amd64\memcpy.asm(40): memcpy_repmovs
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\include\xstring(3277): std::basic_string<char=0x02FF3E45,std::char_traits<char>=0x00007FF6,std::allocator<char> >::append
C:\Projects\airdc-git\leveldb\table\block_builder.cc(101): leveldb::BlockBuilder::Add
C:\Projects\airdc-git\leveldb\table\table_builder.cc(119): leveldb::TableBuilder::Add
C:\Projects\airdc-git\leveldb\db\db_impl.cc(1004): leveldb::DBImpl::DoCompactionWork
C:\Projects\airdc-git\leveldb\db\db_impl.cc(750): leveldb::DBImpl::BackgroundCompaction
C:\Projects\airdc-git\leveldb\db\db_impl.cc(694): leveldb::DBImpl::BackgroundCall
C:\Projects\airdc-git\leveldb\util\env_windows.cc(714): leveldb::`anonymous namespace'::WindowsEnv::BackgroundThreadMain
C:\Projects\airdc-git\leveldb\util\env_windows.cc(656): leveldb::`anonymous namespace'::WindowsEnv::BackgroundThreadEntryPoint
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\include\thread(56): std::thread::_Invoke<std::tuple<void (__cdecl*)(leveldb::`anonymous namespace'::WindowsEnv *)=0x02FB7AFE,leveldb::A0x0119269a::WindowsEnv *>=0x00007FF6,0=0xE5F74BF0,1>
minkernel\crts\ucrt\src\appcrt\startup\thread.cpp(97): thread_start<unsigned int (__cdecl*)(void *)=0x36267344,1>
KERNEL32!0x7FFA36267344: BaseThreadInitThunk
ntdll!0x7FFA381226B1: RtlUserThreadStart
```

### AirDC++ version and architecture (x86 or x64)

AirDC++ 4.21 x64

### Operating System name, version and architecture

Windows 10 Pro 22H2 x64

### Additional information

Start the client, the error come at the same time as I  start it.

**Comment by TehMoff** [comment]
I've started having the same issue. Happens every time I start AirDC. The program closes when or if I press Yes/No. If I just leave the prompt open it seems to work fine.

`Code: c0000006 ( Page error )
Version: AirDC++ 4.21 x64
Build: 4688
Major: 6
Minor: 2
Build: 9200
SP: 0
Type: 1
Time: 2024-03-30 09:52:19
TTH: XVD7Y4Y3ZK7WZVKBIITFBKENJZ4XJD7NOWVPHVY

C:\Projects\airdc-git\leveldb\table\format.cc(97): leveldb::ReadBlock
C:\Projects\airdc-git\leveldb\table\table.cc(177): leveldb::Table::BlockReader
C:\Projects\airdc-git\leveldb\table\two_level_iterator.cc(157): leveldb::`anonymous namespace'::TwoLevelIterator::InitDataBlock
C:\Projects\airdc-git\leveldb\table\two_level_iterator.cc(124): leveldb::`anonymous namespace'::TwoLevelIterator::SkipEmptyDataBlocksForward
C:\Projects\airdc-git\leveldb\table\two_level_iterator.cc(105): leveldb::`anonymous namespace'::TwoLevelIterator::Next
C:\Projects\airdc-git\leveldb\table\merger.cc(77): leveldb::`anonymous namespace'::MergingIterator::Next
C:\Projects\airdc-git\leveldb\db\db_impl.cc(921): leveldb::DBImpl::DoCompactionWork
C:\Projects\airdc-git\leveldb\db\db_impl.cc(750): leveldb::DBImpl::BackgroundCompaction
C:\Projects\airdc-git\leveldb\db\db_impl.cc(694): leveldb::DBImpl::BackgroundCall
C:\Projects\airdc-git\leveldb\util\env_windows.cc(714): leveldb::`anonymous namespace'::WindowsEnv::BackgroundThreadMain
C:\Projects\airdc-git\leveldb\util\env_windows.cc(656): leveldb::`anonymous namespace'::WindowsEnv::BackgroundThreadEntryPoint
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\include\thread(56): std::thread::_Invoke<std::tuple<void (__cdecl*)(leveldb::`anonymous namespace'::WindowsEnv *)=0xF1337AFE,leveldb::A0x0119269a::WindowsEnv *>=0x00007FF6,0=0xD28ADB80,1>
minkernel\crts\ucrt\src\appcrt\startup\thread.cpp(97): thread_start<unsigned int (__cdecl*)(void *)=0x439B7344,1>
KERNEL32!0x7FF9439B7344: BaseThreadInitThunk
ntdll!0x7FF9455826B1: RtlUserThreadStart`

**Comment by Sopor** [comment]
I believe this could be a database issue.
If `/optimizedb` or `/verifydb` doesn't work the only solution is to delete the whole database and hash everything from scratch.

**Comment by hotjo68** [comment]
Update: Downloade AirDC++ and Run a Install ower the old, Problem fixed.!

**Comment by Sopor** [comment]
> Update: Downloaded AirDC++ and Run a Install ower the old, Problem fixed.!

In that case it was not something wrong with AirDC. A reinstall doesn't do anything to the database.
