### ISSUE TITLE
Favorite Hub Properties window not drawn

### ISSUE THREAD

**Issue by j7nj7n** [airdcpp/airdcpp-windows#118]
### Prerequisites

- [X] This is not a [support issue or a question](https://github.com/airdcpp/airdcpp-windows/discussions)
- [X] I performed a [cursory search of the issue tracker](https://github.com/airdcpp/airdcpp-windows/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of AirDC++

### Describe the issue

The window for adding and editing a favorite hub doesn't have its contents drawn correctly on Windows Server 2008 R2. I can't see anything on it until I drag the window outside the screen, and then it becomes filled with garbage data. Tab only cycles between the OK and Cancel buttons, so I can't easily get to the text fields that way. Prior to v4.0 the static labels became white, so it was always slightly special. Other windows like settings or about look normal.

### Expected behavior

I can see the dialog.

### Actual behavior

The dialog is completely invisible.

### Screenshot

![Screenshot_2024-05-03_10-22-18](https://github.com/airdcpp/airdcpp-windows/assets/31337218/ee294a6b-7533-4593-a696-bc0cf2c1e1b1)

### AirDC++ version and architecture (x86 or x64)

4.21 x64

### Operating System name, version and architecture

Windows Server 2008 R2 x64

**Comment by maksis** [comment]
Windows 7/2008 R2 are end-of-life and thus not supported. This issue isn't present in newer versions of Windows.
