### ISSUE TITLE
🐛 [Bug]: AirDC++ 4.22b-23-g59ffd - Another crash

### ISSUE THREAD

**Issue by Sopor** [airdcpp/airdcpp-windows#130]
### Prerequisites

- [X] This is not a [support issue or a question](https://github.com/airdcpp/airdcpp-windows/discussions)
- [X] I performed a [cursory search of the issue tracker](https://github.com/airdcpp/airdcpp-windows/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of AirDC++

### Describe the issue

I wasn't at the computer when it happened, so i don't know what was going on.

### Expected behavior

I wasn't at the computer when it happened, so i don't know what was going on.

### Actual behavior

I wasn't at the computer when it happened, so i don't know what was going on.

### Crash log

```shell
Code: c0000005 ( Access violation )
Version: AirDC++ 4.22b-23-g59ffd x64
Build: 4745
Major: 6
Minor: 2
Build: 9200
SP: 0
Type: 1
Time: 2024-08-18 18:07:54
TTH: 3ECNESFCZEIIMMCVALTFWCE3PFWAUVHKLV7Y6GY

c:\Projects\airdc-windows\airdcpp\airdcpp\Transfer.cpp(148): dcpp::Transfer::addPos
c:\Projects\airdc-windows\airdcpp\airdcpp\UploadManager.cpp(776): dcpp::UploadManager::on
c:\Projects\airdc-windows\airdcpp\airdcpp\UserConnection.cpp(386): dcpp::UserConnection::on
c:\Projects\airdc-windows\airdcpp\airdcpp\BufferedSocket.cpp(325): dcpp::BufferedSocket::threadSendFile
c:\Projects\airdc-windows\airdcpp\airdcpp\BufferedSocket.cpp(474): dcpp::BufferedSocket::checkEvents
c:\Projects\airdc-windows\airdcpp\airdcpp\BufferedSocket.cpp(501): dcpp::BufferedSocket::run
c:\Projects\airdc-windows\airdcpp\airdcpp\Thread.cpp(60): dcpp::Thread::starter
minkernel\crts\ucrt\src\appcrt\startup\thread.cpp(97): thread_start<unsigned int (__cdecl*)(void *)=0x28A87C24,1>
KERNEL32!0x7FFF28A87C24: BaseThreadInitThunk
ntdll!0x7FFF29AED721: RtlUserThreadStart
```

### AirDC++ version and architecture (x86 or x64)

AirDC++ 4.22b-23-g59ffd

### Operating System name, version and architecture

Windows 10 22H2 x64

### Additional information

I have been running the 4.21/4.22b for several month without any crash, so this must have been something from the latest commits that causing this crash.

**Comment by maksis** [comment]
I had the same crash a few times while debugging, it's just a bit difficult to figure out
