### ISSUE TITLE
🐛 [Bug]: Shared bundles is treated as queued (even the color is the queued color)

### ISSUE THREAD

**Issue by Sopor** [airdcpp/airdcpp-windows#138]
### Prerequisites

- [X] This is not a [support issue or a question](https://github.com/airdcpp/airdcpp-windows/discussions)
- [X] I performed a [cursory search of the issue tracker](https://github.com/airdcpp/airdcpp-windows/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of AirDC++

### Describe the issue

When the bundle is sharing it is now treated as it is queued.
You can easy test it by toggle the queued and shared options in another users file list.

### Expected behavior

Check the queued option and uncheck the shared in another users filelist and all the bundles he also have in his share should hide.

### Actual behavior

Bundles will show as they were queued even if the options are set to hide shared bundles.

### AirDC++ version and architecture (x86 or x64)

AirDC++ 4.22b-52-g33c23

### Operating System name, version and architecture

Windows 10 22H2 x64

**Comment by Sopor** [comment]
All these orange should be hidden because i have them in my share.

![image](https://github.com/user-attachments/assets/618e866b-e515-4310-8ec5-c5e22e2047c3)

**Comment by maltenizer** [comment]
Same here. Not registered as shared, still registered as finished/queued.

**Comment by maksis** [comment]
Sorry but I can't reproduce this, share dupes are working just fine. If you actually want to help with testing the client, you should use the common beta builds instead of custom ones.

**Comment by maksis** [comment]
Looks like the issue is that the bundle is never being added in share (it's neither being shown as "Shared" in queue). The dupe color itself is correct.
