### ISSUE TITLE
🐛 [Bug]: Client hangs when hashing

### ISSUE THREAD

**Issue by maltenizer** [airdcpp/airdcpp-windows#141]
### Prerequisites

- [X] This is not a [support issue or a question](https://github.com/airdcpp/airdcpp-windows/discussions)
- [X] I performed a [cursory search of the issue tracker](https://github.com/airdcpp/airdcpp-windows/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of AirDC++

### Describe the issue

When I add a folder to my share, AirDC++ picks up the folder and starts hashing. After some seconds the client hangs and is not responding.

### Expected behavior

Hash the new folder and add it to the share.

### Actual behavior

Starts hashing the new folder but hangs after some seconds. The client is not responding according to task manager. No exceptioninfo.txt is created.

### AirDC++ version and architecture (x86 or x64)

AirDC++ 4.22b-59-g88267 x64

### Operating System name, version and architecture

Windows Server 2022 Datacenter 64-bit

**Comment by maksis** [comment]
See https://github.com/airdcpp/airdcpp-windows/wiki/Client-hangs-(deadlock)

**Comment by maksis** [comment]
Fixed based on a log from another user
