### ISSUE TITLE
Some folders not colored as dupe in search result

### ISSUE THREAD

**Issue by infectormp** [airdcpp/airdcpp-windows#160]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/airdcpp/airdcpp-windows/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of AirDC++
- [X] I'm not reporting an issue that is related to the Web UI/API/extensions (web-related issues should be reported for [AirDC++ Web Client](https://github.com/airdcpp-web/airdcpp-webclient/issues))

### Describe the issue

In search result we got the folder that not colored as dupe
![image](https://github.com/user-attachments/assets/70ababcb-ecf4-48a2-b6d2-ae940a293816)

In the user list this folder colored as dupe
![image](https://github.com/user-attachments/assets/fd42be56-9d99-42e3-b79f-96899adb888c)

### Expected behavior

The folder should be colored as dupe

### Actual behavior

The folder is not coloured as a dupe

### AirDC++ version and architecture (x86 or x64)

4.22b-150

### Operating System name, version and architecture

Windows 11 24H2

**Comment by Sopor** [comment]
And you are sure it doesn't have something to do with `Treat partial dupes similar to exact dupes`?

![image](https://github.com/user-attachments/assets/36f6476f-b391-4f69-92e0-bbf440c895d3)

**Comment by infectormp** [comment]
This option is enabled by default, and if I uncheck it, it won't affect the "buggy" item.

**Comment by infectormp** [comment]
An inside view
![image](https://github.com/user-attachments/assets/4fff8095-e08f-4967-b24e-1a155c612b83)

**Comment by Sopor** [comment]
It is working for me.

**Comment by maksis** [comment]
What's inside the folder doesn't matter as the search has no idea about the content (which is why the filelist won't matter either). The only thing that matters is whether the name of the folder is identical.
