### ISSUE TITLE
Language Install Problems by Start of the Program, Need Help please !

### ISSUE THREAD

**Issue by Frosch641** [airdcpp/airdcpp-windows#164]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/airdcpp/airdcpp-windows/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of AirDC++
- [X] I'm not reporting an issue that is related to the Web UI/API/extensions (web-related issues should be reported for [AirDC++ Web Client](https://github.com/airdcpp-web/airdcpp-webclient/issues))

### Describe the issue

After installing the program you can select the language. When selecting the language the installation crashed.

### Expected behavior

Actually, I should be able to select the language and the installation process should continue. So it would be good if the installation worked again as usual.

### Actual behavior

You can no longer select the language immediately after installation, nor can you use the wizard within the program

### Steps to reproduce the behavior (if applicable)
1. Installing AirDC++ 4.21
2. Try to set German language
3. Abort Installation

### Screenshot/video

https://github.com/user-attachments/assets/ee45a97a-3fa3-43ac-b754-656ea66fdfa9

### Crash/hang log

```shell
Code: c0000002 ( Unknown )
Version: AirDC++ 4.21 x64
Build: 4688
Major: 6
Minor: 2
Build: 9200
SP: 0
Type: 1
Time: 2024-11-16 16:03:34
TTH: XVD7Y4Y3ZK7WZVKBIITFBKENJZ4XJD7NOWVPHVY

KERNELBASE!0x7FFC6D6F831A: RaiseException
C:\Projects\airdc-git\windows\LanguageDownloadDlg.h(80): LanguageDownloadDlg::close
C:\Projects\airdc-git\windows\Wizard.h(46): SetupWizard::ProcessWindowMessage
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\atlmfc\include\atlwin.h(3576): ATL::CWindowImplBaseT<WTL::CListViewCtrlT<ATL::CWindow>=0x5CF51088,ATL::CWinTraits<1442840576=0x00007FFC,0> >::WindowProc
atlthunk!0x7FFC5CF51088: ?
USER32!0x7FFC6E0A5801: CallWindowProcW
USER32!0x7FFC6E0A334D: IsWindowUnicode
COMCTL32!0x7FFC52C7236D: LoadIconWithScaleDown
COMCTL32!0x7FFC52CE44D7: TaskDialogIndirect
COMCTL32!0x7FFC52CC4327: CreatePropertySheetPageA
C:\Projects\airdc-git\windows\WTL\atldlgs.h(3937): WTL::CPropertySheetImpl<TreePropertySheet=0x44E1F735,WTL::CPropertySheetWindow>::DoModal
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\include\functional(839): std::_Func_impl_no_alloc<``WinClient::wizardFGetter'::`2'::<lambda_1>::operator()'::`2'::<lambda_1>,void>::_Do_call
C:\Projects\airdc-git\windows\SplashWindow.h(37): SplashWindow::ProcessWindowMessage
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\atlmfc\include\atlwin.h(3576): ATL::CWindowImplBaseT<WTL::CListViewCtrlT<ATL::CWindow>=0x5CF51028,ATL::CWinTraits<1442840576=0x00007FFC,0> >::WindowProc
atlthunk!0x7FFC5CF51028: ?
USER32!0x7FFC6E0A5801: CallWindowProcW
USER32!0x7FFC6E0A334D: IsWindowUnicode
C:\Projects\airdc-git\windows\WTL\atlapp.h(666): WTL::CMessageLoop::Run
C:\Projects\airdc-git\windows\WinClient.cpp(456): WinClient::run
C:\Projects\airdc-git\windows\main.cpp(337): wWinMain
D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl(288): __scrt_common_main_seh
KERNEL32!0x7FFC6DD3DBE7: BaseThreadInitThunk
ntdll!0x7FFC6FC5FBEC: RtlUserThreadStart
```

### AirDC++ version and architecture (x86 or x64)

4.21 x64

### Operating System name, version and architecture

Windows 11 Version 24H2 x64

### Additional information

So far I have always been able to install airdc++ without any problems, it would be great if the bug could be fixed

**Comment by maksis** [comment]
Seems like the current beta doesn't crash. I'd expect the next stable version to be released relatively soon.
