### ISSUE TITLE
Crash - dcpp::Transfer::getToken

### ISSUE THREAD

**Issue by Sopor** [airdcpp/airdcpp-windows#166]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/airdcpp/airdcpp-windows/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of AirDC++
- [X] I'm not reporting an issue that is related to the Web UI/API/extensions (web-related issues should be reported for [AirDC++ Web Client](https://github.com/airdcpp-web/airdcpp-webclient/issues))

### Describe the issue

I was not at the computer when it crashed ...

### Expected behavior

.

### Actual behavior

.

### Crash/hang log

```shell
Code: c0000005 ( Access violation )
Version: AirDC++ 4.22b-174-g01f0d x64
Build: 4895
Major: 6
Minor: 2
Build: 9200
SP: 0
Type: 1
Time: 2024-11-16 14:31:39
TTH: 5BPQXLUQP6YTQIH36RYA4KCZRA3F34A237ODRCQ

C:\Projects\airdc-windows\airdcpp\airdcpp\transfer\Transfer.cpp(42): dcpp::Transfer::getToken
c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\functional(874): std::_Func_impl_no_alloc<`dcpp::UploadManager::getAsyncWrapper'::`2'::<lambda_1>=0x03C409D2,void>::_Do_call
C:\Projects\airdc-windows\airdcpp\airdcpp\connection\socket\BufferedSocket.cpp(493): dcpp::BufferedSocket::checkEvents
C:\Projects\airdc-windows\airdcpp\airdcpp\connection\socket\BufferedSocket.cpp(517): dcpp::BufferedSocket::run
C:\Projects\airdc-windows\airdcpp\airdcpp\core\thread\Thread.cpp(59): dcpp::Thread::starter
minkernel\crts\ucrt\src\appcrt\startup\thread.cpp(97): thread_start<unsigned int (__cdecl*)(void *)=0x900E7C24,1>
KERNEL32!0x7FFE900E7C24: BaseThreadInitThunk
ntdll!0x7FFE90C8D721: RtlUserThreadStart
```

### AirDC++ version and architecture (x86 or x64)

AirDC++ 4.22b-174

### Operating System name, version and architecture

Windows 10 22H2 x64

**Comment by maksis** [comment]
Probably related to https://github.com/airdcpp-web/airdcpp-webclient/issues/485
