### ISSUE TITLE
Transient network error breaks directory monitoring

### ISSUE THREAD

**Issue by Xon** [airdcpp/airdcpp-windows#2]
When using AirDC++ against a network fileshare (VM exposing a host's share), if the VM is paused or saved this interrupts network connectivity.

File handles are automatically reopened, but the directory monitoring is not;
Log message;
  [16:20:37] A failed directory X:\ has been removed from monitoring: An unexpected network error occurred. (code: 59) 

Currently the only way to re-apply those directory monitoring is to toggle the functionality off and then back on.

**Comment by maksis** [comment]
There's no periodic file list refresh by default because of monitoring so you can't rely on that. Readding directories isn't an issue and it doesn't require disk access; the issue is to detect when the monitoring is not working because Windows won't always give an error in those cases.

**Comment by Xon** [comment]
Ah true. 

From a usability perspective, it would be nice to just issue a manual refresh and the app fix it's internal state up vs having to restart the entire application.

Sadly, actually detecting this error is very much a manual thing for a host of reasons.
