### ISSUE TITLE
Does not save after restart

### ISSUE THREAD

**Issue by ghost** [airdcpp/airdcpp-windows#41]
The position and size of the window (if you to stretch to the edges of the desktop), multi-line insertion and disconnection of the transmission window. I use beta portable version and windows 10.

**Comment by maksis** [comment]
What's the exact client version?

**Comment by KCAHDEP** [comment]
![image](https://user-images.githubusercontent.com/17965210/56474844-58d20700-6488-11e9-8d11-bf59ede03041.png)

**Comment by maksis** [comment]
I can't reproduce any position/size saving issues with version 3.55b

**Comment by KCAHDEP** [comment]
maybe you look through the teamweaver? I always repeat.

**Comment by maksis** [comment]
Sure. You can join the hub adcs://web-dev.airdcpp.net:1511 for further discussion.

**Comment by maksis** [comment]
I can confirm some of the issue when then options "Minimize at program startup" and "Minimize to tray" are enabled.

- Transferview doesn't work (the latest version of ApexDC++ seems to have the same issue)
- Multiline insertion state has never been persisted between restarts, so I don't see any issue there
- Maximized window size doesn't seem to be applied after restarting the app but it seems to be the same with version 3.54

**Comment by KCAHDEP** [comment]
Will it be possible to fix all this and add multiline mode saving?

**Comment by maksis** [comment]
> Will it be possible to fix all this and add multiline mode saving?

It's possible that fixes will be made. Multiline saving is up to @night-z to decide.

**Comment by Sopor** [comment]
User is ghosted!
