### ISSUE TITLE
Download magnet links without filenames via search

### ISSUE THREAD

**Issue by Terebi42** [airdcpp/airdcpp-windows#53]
When clicking on a magnet link which does not have a name, airdc gives an error saying that the file already exists on disk, even though it doesn't.  I think this is because there is no filename to check against.

You can search for the file, and then click the first result. I'd like this to be automatic, so I don't have to close all the search tabs that pop open from doing this.

**Comment by maksis** [comment]
Where are those magnet links without a name coming from?

**Comment by Terebi42** [comment]
I have emailed you additional info

**Comment by maksis** [comment]
It's still no clear that why the links are being generated without a filename, as adding the filename would be the easiest to way to fix this (and I haven't seen such links being generated before).

Have you asked the person responsible for generating those links whether the filename could be added?

**Comment by RoLex** [comment]
#close
