### ISSUE TITLE
exception on refresh 

### ISSUE THREAD

**Issue by infectormp** [airdcpp/airdcpp-windows#57]
Just got an exception. This is first time for a very long stable period. 
Maybe caused by settings change in Advanced sharing extension. Before a crash i was enabled experimental future **Auto-resume refresh...**

Code: c0000005 ( Access violation )
Version: AirDC++ 4.10 x64
Build: 4504
Major: 6
Minor: 2
Build: 9200
SP: 0
Type: 1
Time: 2021-02-27 15:30:51
TTH: L2REWBCPVTTMLH77KC3UZEAN2OVJHOCT5NQ4R2Y

C:\Projects\airdc-git\airdcpp-webapi\api\ShareUtils.cpp(50): webserver::ShareUtils::serializeItem
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\functional(947): std::_Func_impl_no_alloc<nlohmann::basic_json<std::map=0xB0F4CA24,std::vector=0x00007FF7,std::basic_string<char=0xC6B82C00,std::char_traits<char>=0x00000191,std::allocator<char> >=0xB15E0D60,bool=0x00007FF7,__int64=0x3B9FF109,unsigned __int64=0x00000081,double=0x8E752E10,std::allocator=0x00000191,nlohmann::adl_serializer=0x90484A70,std::vector<unsigned char=0x00000191,std::allocator<unsigned char> > > (__cdecl*)(std::shared_ptr<webserver::WebUser> const &=0x3B9F0000,int) noexcept=0x00000081,nlohmann::basic_json<std::map=0x00000000,std::vector=0x00000000,std::basic_string<char=0x00000000,std::char_traits<char>=0x00000000,std::allocator<char> >=0x00000000,bool=0x00000000,__int64=0x00000000,unsigned __int64=0x00000000,double=0x00000020,std::allocator=0x00000000,nlohm

![image](https://user-images.githubusercontent.com/9958813/109387262-6d4b7a00-7911-11eb-9515-f886ef8b5ba7.png)

**Comment by maksis** [comment]
Is that the full exception info? Looks like it's cut for some reason, making it harder to locate the issue.

**Comment by infectormp** [comment]
Yes, exception info is full.

**Comment by maksis** [comment]
That's a shame. Please post an update if it crashes again.

**Comment by maksis** [comment]
Looks like it hasn't happened again
