### ISSUE TITLE
How to see the TTH list of one's share in clear?

### ISSUE THREAD

**Issue by penpexgit** [airdcpp/airdcpp-windows#58]
Hello, 
I am not sure if this is the right place to ask this, but I could not register on the forum for some reason (never got the email) so I am asking here.

I am trying out AirDC++ to see how it is compares to regular DC++ that I am currently running, and I have a question.
I noticed a difference in the storage of the list of TTH of one's share.
In DC++, it's all in clear in one file (`files.xml`), along with the file names, and directory structure (thus making it easy to parse).
In AirDC++, on Windows, the files' names are in some files in the `ShareCache` directory if I understood correctly, but with no TTH info, and then there is a `HashData` folder containing some `*.ldb` files.
I assume these contain the TTH info, but in a non readily readable format (a LevelDB database format if I followed).

How would one find a way to decipher these files **to get the TTH list of their share**?
I'm asking because I can currently run Python scripts that parse the `files.xml` from the DC++ config folder, and get TTH info that way, but so far I haven't found a solution to do that with AirDC++.
If there is a way directly through AirDC++ to export such a list, I'm all ears, but I haven't found anything like that.

(I tried using the Python library [plyvel](https://github.com/wbolster/plyvel) to open these `*.ldb` files, but I cannot decode the byte structure of the keys or values I get using `UTF-8`, or `latin-1`, and I was reaching the extent of my abilities so far, so I gave up).

Thank you for your time.

**Comment by maksis** [comment]
> In DC++, it's all in clear in one file (files.xml), along with the file names, and directory structure (thus making it easy to parse).
In AirDC++, on Windows, the files' names are in some files in the ShareCache directory if I understood correctly, but with no TTH info, and then there is a HashData folder containing some *.ldb files.

`files.xml` and `ShareCache` are being used  for different purposes. `files.xml` is the filelist that is being uploaded to other users while `ShareCache` is used for storing the share structure that can be loaded on startup without iterating over the directories on disk similar to DC++. `ShareCache` won't contain redundant data (such as TTHs) that can be looked up from the hash database.

As AirDC++ is also capable of uploading filelists, it will also create `files.xml`, but only when the filelist is being requested by another user. However, there's an undocumented command `/generatelist` that you can use to generate the file manually, which is probably what you want.

If you want to parse TTHs from the LevelDB files, it would actually be better to use the `FileIndex` directory. The keys of that database are lowercase file paths. It uses the following value format: 

- 8 bytes representing the last known modification time of the file (numeric)
- 24 bytes representing the TTH of the file. You can encode hash to Base32 to get the string representation.
- 8 bytes representing the file size

**Comment by penpexgit** [comment]
Thank you for your answer, the `/generatelist` command was exactly what I needed.
