### ISSUE TITLE
AirDC crushes on file open with OEM-US encoding

### ISSUE THREAD

**Issue by infectormp** [airdcpp/airdcpp-windows#60]
AirDC crushes when trying to open file with OEM-US encoding

Code: e06d7363 ( Unknown )
Version: AirDC++ 4.10 x64
Build: 4504
Major: 6
Minor: 2
Build: 9200
SP: 0
Type: 1
Time: 2021-05-05 23:03:17
TTH: L2REWBCPVTTMLH77KC3UZEAN2OVJHOCT5NQ4R2Y

KERNELBASE!0x7FFACF374B59: RaiseException
d:\agent\_work\63\s\src\vctools\crt\vcruntime\src\eh\frame.cpp(1391): __FrameHandler4::CxxCallCatchBlock
ntdll!0x7FFAD1C51406: RtlCaptureContext2
AirDC!0x7FF6A9A2A92A: bool boost::re_detail_107500::perl_matcher<class std::_String_const_iterator<class std::_String_val<struct std::_Simple_types<wchar_t> > >,class std::allocator<struct boost::sub_match<class std::_String_const_iterator<class std::_String_val<struct std::_Simple_types<wchar_t> > > > >,struct boost::regex_traits<wchar_t,class boost::w32_regex_traits<wchar_t> > >::find_imp(void)
C:\Projects\airdc-git\boost\boost\regex\v4\regex_search.hpp(56): boost::regex_search<std::_String_const_iterator<std::_String_val<std::_Simple_types<wchar_t> > >=0xA976F5C6,std::allocator<boost::sub_match<std::_String_const_iterator<std::_String_val<std::_Simple_types<wchar_t> > > > >=0x00007FF6,wchar_t=0x9AC979D0,boost::regex_traits<wchar_t=0x000002C6,boost::w32_regex_traits<wchar_t> > >
C:\Projects\airdc-git\boost\boost\regex\v4\regex_search.hpp(43): boost::regex_search<std::_String_const_iterator<std::_String_val<std::_Simple_types<wchar_t> > >=0xA976414A,std::allocator<boost::sub_match<std::_String_const_iterator<std::_String_val<std::_Simple_types<wchar_t> > > > >=0x00007FF6,wchar_t=0xBA6812A0,boost::regex_traits<wchar_t=0x000002C6,boost::w32_regex_traits<wchar_t> > >
C:\Projects\airdc-git\windows\RichTextBox.cpp(559): RichTextBox::FormatEmoticonsAndLinks
C:\Projects\airdc-git\windows\RichTextBox.cpp(181): RichTextBox::AppendText
C:\Projects\airdc-git\windows\TextFrame.cpp(147): TextFrame::OnCreate
C:\Projects\airdc-git\windows\TextFrame.h(66): TextFrame::ProcessWindowMessage
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\atlmfc\include\atlwin.h(3572): ATL::CWindowImplBaseT<WTL::CMDIWindow=0xBCBD2108,ATL::CWinTraits<1456406528=0x00007FFA,64> >::WindowProc
atlthunk!0x7FFABCBD2108: ?
USER32!0x7FFAD0B9E858: CallWindowProcW
USER32!0x7FFAD0B9E3DC: DispatchMessageW
USER32!0x7FFAD0BB2BF7: InitDManipHook
ntdll!0x7FFAD1C50B54: KiUserCallbackDispatcher
win32u!0x7FFACFB31EC4: NtUserCreateWindowEx
USER32!0x7FFAD0B97D8B: CreateWindowExW
USER32!0x7FFAD0B97958: CreateWindowExW
USER32!0x7FFAD0B977A2: CreateWindowExW
C:\Projects\airdc-git\windows\WTL\atlframe.h(325): WTL::CFrameWindowImplBase<WTL::CMDIWindow=0xA984256A,ATL::CWinTraits<1456406528=0x00007FF6,64> >::Create
C:\Projects\airdc-git\windows\WTL\atlframe.h(1450): WTL::CMDIChildWindowImpl<TextFrame=0xA9841340,WTL::CMDIWindow=0x00007FF6,ATL::CWinTraits<1456406528=0x89A6E5D0,64> >::CreateEx
C:\Projects\airdc-git\windows\TextFrame.cpp(94): TextFrame::openWindow
C:\Projects\airdc-git\windows\TextFrame.cpp(85): TextFrame::viewText
C:\Projects\airdc-git\windows\TextFrame.cpp(75): TextFrame::openFile
C:\Projects\airdc-git\windows\MainFrm.h(97): MainFrame::ProcessWindowMessage
C:\Projects\airdc-git\windows\WTL\atlframe.h(1229): WTL::CMDIFrameWindowImpl<MainFrame=0xBCBD1058,WTL::CMDIWindow=0x00007FFA,ATL::CWinTraits<114229248=0x00000000,262400> >::MDIFrameWindowProc
atlthunk!0x7FFABCBD1058: ?
USER32!0x7FFAD0B9E858: CallWindowProcW
USER32!0x7FFAD0B9E4EE: CallWindowProcW
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\atlmfc\include\atlwin.h(4623): ATL::CContainedWindowT<ATL::CWindow=0xBCBD10E8,ATL::CWinTraits<1442840576=0x00007FFA,0> >::WindowProc
atlthunk!0x7FFABCBD10E8: ?
USER32!0x7FFAD0B9E858: CallWindowProcW
USER32!0x7FFAD0B9E299: DispatchMessageW
C:\Projects\airdc-git\windows\WTL\atlapp.h(666): WTL::CMessageLoop::Run
C:\Projects\airdc-git\windows\WinClient.cpp(454): WinClient::run
C:\Projects\airdc-git\windows\main.cpp(337): wWinMain
d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl(288): __scrt_common_main_seh
KERNEL32!0x7FFAD0247034: BaseThreadInitThunk
ntdll!0x7FFAD1C02651: RtlUserThreadStart

**Comment by maksis** [comment]
Does this still happen with the latest beta?

**Comment by infectormp** [comment]
Look like no. Trayed on different files witout success.
