### ISSUE TITLE
Windows & Ubuntu Samba Issue

### ISSUE THREAD

**Issue by zeeter82** [airdcpp/airdcpp-windows#64]
I'm honestly not sure if this is a Windows 10, Ubuntu 20.04, or AirDC++ issue (or a combination), but it's very frustrating and I've spent days trying different settings and options to try and resolve it.  I'm hoping someone here might be able to point me in the right direction and if this is in fact a bug in AirDC++, maybe it can be fixed.

I have a file server (running Ubuntu 20.04 - latest updates etc.) with a writable samba share that I have set as a download location in my AirDC++ Windows client (v4.10).  Everything works as it should and I can download whatever I need to the share, but when accessing the share from Win10 (file explorer) a lot of the times the smaller ascii/txt based files (nfo etc.) won't open if I double click them.  I get the "directory name is invalid" error.  But I'm able to successfully right click the file and open with notepad or other app.  I'm also able to copy that file to my local Win10 desktop and open it fine there as well.  And then if I take that file that I copied to the desktop and copy it back to the original samba share directory and overwrite that file, it fixes it somehow.  I'm then able to open the file by double clicking on it normally.

The reason this is so annoying is that the release validator extension complains about the nfo files being missing when in fact they are there, but in some type of "stale" state and can't be read until  I manually fix them (usually copying them locally and then copying them back to the samba share).

Here is a couple links describing a very similar issue that I'm having, but this is on a Synology NAS.  
1. https://answers.microsoft.com/en-us/insider/forum/all/message-the-directory-name-is-invalid-when-opening/28e6e31e-7785-45f5-85a9-5e30bdde9562?page=1

2.  https://social.technet.microsoft.com/Forums/en-US/f8cdb6d8-fae0-4661-ac1e-448ccbbafdd3/quotthe-directory-name-is-invalidquot-when-opening-some-files-on-a-mounted-drive-to-my-synology?forum=win10itpronetworking

Any help is appreciated and if I'm wrong by posting an issue like this, then a mod/dev can absolutely remove it.

**Comment by Sopor** [comment]
Have you tried adding `oplocks = False` to smb.conf ?

You can read more about it [here](https://www.linuxtopia.org/online_books/network_administration_guides/samba_reference_guide/24_locking_08.html)

You could try exclude those network drives in Defender or try exclude *.txt and *.nfo files only. Antivirus programs can create all kind of weird issues. Defender will support UNC paths `\\computername\share` if you want to exclude the whole network drive.

I don't know if it will help, but it is worth a chance.

**Comment by zeeter82** [comment]
Thanks for those suggestions.  I tried them both and it didn't make a difference.  Still getting random "directory name is invalid" errors on nfo/sfv files.

**Comment by zeeter82** [comment]
So this issue still exists for me after upgrading to 4.11.  Is there anything I can change with file download buffer sizes? Socket sizes?  Are there any advanced options I can try to maybe resolve this?  This really only seems to happen when downloading small files to this share through AirDC.

**Comment by Sopor** [comment]
This is probably a Windows issue. Many users have issues with the network after updating Windows 10.

That is why i still running 1909 :)

Try install a new fresh Windows 10 (21H1) in a virtual machine (VirtualBox or Vmware) to see if you have the same issue.

**Comment by maksis** [comment]
Is this still an issue with Windows 11?

**Comment by maksis** [comment]
Closing as there are no comments
