### ISSUE TITLE
Exception on startup

### ISSUE THREAD

**Issue by infectormp** [airdcpp/airdcpp-windows#65]
Exception on startup after upgrade to 4.11 from dev build.

Code: c0000005 ( Access violation )
Version: AirDC++ 4.11 x64
Build: 4560
Major: 6
Minor: 2
Build: 9200
SP: 0
Type: 1
Time: 2021-09-21 18:19:35
TTH: UXOVWERYSCUDKOX6YGZLLA4T4ZRMG2NWDEQIEXI

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xhash(1679): std::_Hash<std::_Umap_traits<std::basic_string<char=0xC5746030,std::char_traits<char>=0x00000247,std::allocator<char> > *=0xB4E3CDF0,boost::intrusive_ptr<dcpp::ShareManager::Directory>=0x00000247,std::_Uhash_compare<std::basic_string<char=0x00310001,std::char_traits<char>=0x00000000,std::allocator<char> > *=0x00009365,dcpp::StringPtrHash=0x00000000,dcpp::StringPtrEq>=0xDC5F9FE1,std::allocator<std::pair<std::basic_string<char=0x90001800,std::char_traits<char>=0x6F636E69,std::allocator<char> > * const=0x676E696D,boost::intrusive_ptr<dcpp::ShareManager::Directory> > >=0x00000000,1> >::_Forced_reh

**Comment by RoLex** [comment]
Please test stable 4.11 or 4.20 to be sure. Developer builds are developer builds, they can be dirty. If you have resolved the issue, please close this issue.
