### ISSUE TITLE
4.12 Crash

### ISSUE THREAD

**Issue by infectormp** [airdcpp/airdcpp-windows#69]
Just found this crash when back to may PC

Code: c0000005 ( Access violation )
Version: AirDC++ 4.12b-9-gbd9a1 x64
Build: 4581
Major: 6
Minor: 2
Build: 9200
SP: 0
Type: 1
Time: 2022-02-27 17:19:31
TTH: AD643BGQTCL3TUNYJYSSISHBEHMDKWIOF76KKHQ

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\memory(1129): std::_Ref_count<dcpp::DirectoryListing::VirtualDirectory>::_Destroy
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\xtree(745): std::_Tree_val<std::_Tree_simple_types<std::pair<unsigned int const =0x61708B6F,std::shared_ptr<dcpp::SearchInstance> > > >::_Erase_tree<std::allocator<std::_Tree_node<std::pair<unsigned int const =0x00007FF6,std::shared_ptr<dcpp::SearchInstance> >=0x2344B040,void *> > >
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\xtree(745): std::_Tree_val<std::_Tree_simple_types<std::pair<unsigned int const =0x61708B6F,std::shared_ptr<dcpp::SearchInstance> > > >::_Erase_tree<std::allocator<std::_Tree_node<std::pair<unsigned int const =0x00007FF6,std::shared_ptr<dcpp::SearchInstance> >=0x2344B040,void *> > >
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\xtree(745): std::_Tree_val<std::_Tree_simple_types<std::pair<unsigned int const =0x61708B6F,std::shared_ptr<dcpp::SearchInstance> > > >::_Erase_tree<std::allocator<std::_Tree_node<std::pair<unsigned int const =0x00007FF6,std::shared_ptr<dcpp::SearchInstance> >=0x23355BD0,void *> > >
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\xtree(745): std::_Tree_val<std::_Tree_simple_types<std::pair<unsigned int const =0x61708B6F,std::shared_ptr<dcpp::SearchInstance> > > >::_Erase_tree<std::allocator<std::_Tree_node<std::pair<unsigned int const =0x00007FF6,std::shared_ptr<dcpp::SearchInstance> >=0x23355BD0,void *> > >
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\xtree(745): std::_Tree_val<std::_Tree_simple_types<std::pair<unsigned int const =0x61708B6F,std::shared_ptr<dcpp::SearchInstance> > > >::_Erase_tree<std::allocator<std::_Tree_node<std::pair<unsigned int const =0x00007FF6,std::shared_ptr<dcpp::SearchInstance> >=0x23355BD0,void *> > >
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\xtree(745): std::_Tree_val<std::_Tree_simple_types<std::pair<unsigned int const =0x61708B6F,std::shared_ptr<dcpp::SearchInstance> > > >::_Erase_tree<std::allocator<std::_Tree_node<std::pair<unsigned int const =0x00007FF6,std::shared_ptr<dcpp::SearchInstance> >=0x23355BD0,void *> > >
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\xtree(745): std::_Tree_val<std::_Tree_simple_types<std::pair<unsigned int const =0x61785A7A,std::shared_ptr<dcpp::SearchInstance> > > >::_Erase_tree<std::allocator<std::_Tree_node<std::pair<unsigned int const =0x00007FF6,std::shared_ptr<dcpp::SearchInstance> >=0x23355BD0,void *> > >
C:\Projects\airdc-git\airdcpp\airdcpp\DirectoryListing.cpp(689): dcpp::DirectoryListing::Directory::~Directory
AirDC!0x7FF6617847C4: dcpp::DirectoryListing::Directory::`scalar deleting destructor'
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\xtree(745): std::_Tree_val<std::_Tree_simple_types<std::pair<unsigned int const =0x61708B6F,std::shared_ptr<dcpp::SearchInstance> > > >::_Erase_tree<std::allocator<std::_Tree_node<std::pair<unsigned int const =0x00007FF6,std::shared_ptr<dcpp::SearchInstance> >=0x2A5A2180,void *> > >
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\xtree(745): std::_Tree_val<std::_Tree_simple_types<std::pair<unsigned int const =0x61708B6F,std::shared_ptr<dcpp::SearchInstance> > > >::_Erase_tree<std::allocator<std::_Tree_node<std::pair<unsigned int const =0x00007FF6,std::shared_ptr<dcpp::SearchInstance> >=0x2C546060,void *> > >
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\xtree(745): std::_Tree_val<std::_Tree_simple_types<std::pair<unsigned int const =0x61785A7A,std::shared_ptr<dcpp::SearchInstance> > > >::_Erase_tree<std::allocator<std::_Tree_node<std::pair<unsigned int const =0x00007FF6,std::shared_ptr<dcpp::SearchInstance> >=0x2214CF80,void *> > >
C:\Projects\airdc-git\airdcpp\airdcpp\DirectoryListing.cpp(689): dcpp::DirectoryListing::Directory::~Directory
AirDC!0x7FF6617847C4: dcpp::DirectoryListing::Directory::`scalar deleting destructor'
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\xtree(745): std::_Tree_val<std::_Tree_simple_types<std::pair<unsigned int const =0x61708B6F,std::shared_ptr<dcpp::SearchInstance> > > >::_Erase_tree<std::allocator<std::_Tree_node<std::pair<unsigned int const =0x00007FF6,std::shared_ptr<dcpp::SearchInstance> >=0x8A8D7740,void *> > >
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\xtree(745): std::_Tree_val<std::_Tree_simple_types<std::pair<unsigned int const =0x61708B6F,std::shared_ptr<dcpp::SearchInstance> > > >::_Erase_tree<std::allocator<std::_Tree_node<std::pair<unsigned int const =0x00007FF6,std::shared_ptr<dcpp::SearchInstance> >=0x79852210,void *> > >
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\xtree(745): std::_Tree_val<std::_Tree_simple_types<std::pair<unsigned int const =0x61708B6F,std::shared_ptr<dcpp::SearchInstance> > > >::_Erase_tree<std::allocator<std::_Tree_node<std::pair<unsigned int const =0x00007FF6,std::shared_ptr<dcpp::SearchInstance> >=0x79852210,void *> > >
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\xtree(745): std::_Tree_val<std::_Tree_simple_types<std::pair<unsigned int const =0x61708B6F,std::shared_ptr<dcpp::SearchInstance> > > >::_Erase_tree<std::allocator<std::_Tree_node<std::pair<unsigned int const =0x00007FF6,std::shared_ptr<dcpp::SearchInstance> >=0x79852210,void *> > >
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\xtree(745): std::_Tree_val<std::_Tree_simple_types<std::pair<unsigned int const =0x61785A7A,std::shared_ptr<dcpp::SearchInstance> > > >::_Erase_tree<std::allocator<std::_Tree_node<std::pair<unsigned int const =0x00007FF6,std::shared_ptr<dcpp::SearchInstance> >=0x79852210,void *> > >
C:\Projects\airdc-git\airdcpp\airdcpp\DirectoryListing.cpp(689): dcpp::DirectoryListing::Directory::~Directory
AirDC!0x7FF6617847C4: dcpp::DirectoryListing::Directory::`scalar deleting destructor'
C:\Projects\airdc-git\windows\DirectoryListingFrm.cpp(2047): DirectoryListingFrame::ItemInfo::~ItemInfo
C:\Projects\airdc-git\windows\DirectoryListingFrm.cpp(230): DirectoryListingFrame::~DirectoryListingFrame
AirDC!0x7FF66140ACB0: DirectoryListingFrame::`scalar deleting destructor'
C:\Projects\airdc-git\windows\FlatTabCtrl.h(765): MDITabChildWindowImpl<AutoSearchFrame=0x6132E2F5,WTL::CMDIWindow=0x00007FF6,ATL::CWinTraits<1456406528=0x16883E80,64> >::OnFinalMessage
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\atlmfc\include\atlwin.h(3596): ATL::CWindowImplBaseT<WTL::CMDIWindow=0x6B852A02,ATL::CWinTraits<1456406528=0x00007FFF,64> >::WindowProc
atlthunk!0x7FFF6B852A02: AtlThunk_DataToCode
USER32!0x7FFF90C51C4C: CallWindowProcW
USER32!0x7FFF90C50EA6: DispatchMessageW
C:\Projects\airdc-git\windows\WTL\atlapp.h(666): WTL::CMessageLoop::Run
C:\Projects\airdc-git\windows\WinClient.cpp(459): WinClient::run
C:\Projects\airdc-git\windows\main.cpp(337): wWinMain
d:\a01\_work\20\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl(288): __scrt_common_main_seh
KERNEL32!0x7FFF900B54E0: BaseThreadInitThunk
ntdll!0x7FFF9102485B: RtlUserThreadStart

**Comment by RoLex** [comment]
Please try AirDC++ 4.20, because version 4.12 seems to be something in between :-P

**Comment by infectormp** [comment]
@RoLex if do not touch issue for a long period of time, the issue probably will resolve it's self
