### ISSUE TITLE
Someone please create a dark skin for AirDC++ /  issue with settings\sharing

### ISSUE THREAD

**Issue by mandrixoh1** [airdcpp/airdcpp-windows#72]
The software runs 24/7 for me and overall does what I need. But the bright white screen about blinds me at night. In my old age my eyes have become very light sensitive.

Is AirDC++ still actively being developed/maintained? The forum is useless for me as I can't even join and was even told it's all screwed up. Seems like no one much cares about it I guess.

The one issue I keep having is opening settings\sharing, the screen locks up for a while like it's gonna crash but eventually does reveal the shared folders after a few minutes in purgatory. Maybe it just takes time to do it's thing, IDK.

**Comment by Sopor** [comment]
Have you tried the ZoolutioN theme?

![17](https://user-images.githubusercontent.com/5789283/192788452-30098b34-02b2-4917-bb32-8735cdf4c5e8.png)

**Comment by Sopor** [comment]
> The one issue I keep having is opening settings\sharing, the screen locks up for a while like it's gonna crash but eventually does reveal the shared folders after a few minutes in purgatory. Maybe it just takes time to do it's thing, IDK.

You can try uncheck `Show directory tree` and see if that makes it faster.

![image](https://user-images.githubusercontent.com/5789283/192789777-aa845b87-3b11-49b3-a2b7-b78e0bfd4071.png)

**Comment by ryehamstrawberry** [comment]
As Sopor suggested, ZoolutioN is one option and there's also [Kunligt](https://www.airdcpp.net/customizations/themes/kungligt-theme).

**Comment by mandrixoh1** [comment]
Thanks!

Sorry I haven’t been available to check replies.

**Comment by mandrixoh1** [comment]
Ah. Apparently you have to register on the forum to download themes?
I've never been able to register, always throws an error.
Any themes posted elsewhere?

**Comment by ryehamstrawberry** [comment]
> Ah. Apparently you have to register on the forum to download themes?

You don't need to register for anything to download themes.
[Please look before you post, this entire thread should be closed](https://i.imgur.com/KCNZCwW.png).

**Comment by Sopor** [comment]
ZoolutioN is a part of AirDC already. If you open setting you will find it under `Appearance/Colors & fonts/Themes`.

**Comment by mandrixoh1** [comment]
Thank you! I did not know that.

Many thanks to all that responded. Problem solved.
