### ISSUE TITLE
v4.12b NFO viewing error

### ISSUE THREAD

**Issue by ryehamstrawberry** [airdcpp/airdcpp-windows#73]
Although I personally have not encountered this issue, I keep seeing users complain about it.

Description:
when u read nfo, u see 100+ random nicknames on mainchat, and then "File Not Available" (_sic_)
But if doing search or nfo check, random hub show list of 100+ of users and next to the nick "File Not Available" (_sic_)

---
Version: AirDC++ 4.12b-9-gbd9a1 x64

**Comment by maksis** [comment]
This is a problem with the hubsoft not forwarding the searches correctly, not a client issue
