### ISSUE TITLE
SECURITY WARNING: received a DSCH message that should have been sent to a different user.

### ISSUE THREAD

**Issue by ryehamstrawberry** [airdcpp/airdcpp-windows#76]
As of late I've received many user reports claiming to have seen this message:
_*** SECURITY WARNING: received a DSCH message that should have been sent to a different user. This should never happen. Please inform the hub owner in order to get the security issue fixed._

Unfortunately, none of the users are able to report what seems to be triggering the message.
I'm hoping others will reply with their experiences and include their activity immediately before encountering the message.

The common thread among all users who have reported this error is their usage of AirDC++ 4.12b-47-gb46b2 and presence on hubs running Luadch v2.24 [RC4].
Users on v4.11 stable have not yet reported this error on hubs running Luadch v2.24 [RC4].

I've been told by a particular AirDC++/Luadch tester that this error is originating from AirDC++, for what it's worth.

Additional reports are encouraged.

**Comment by maksis** [comment]
Duplicate of https://github.com/airdcpp/airdcpp-windows/issues/73 and https://github.com/luadch/luadch/issues/197

I believe that this bug was introduced in Luadch v2.23 RC10 so downgrading to an older Luadch version will help
