### ISSUE TITLE
Release names beginning with lowercase characters are not recognized as clickable releases

### ISSUE THREAD

**Issue by ryehamstrawberry** [airdcpp/airdcpp-windows#80]
All release names beginning with a lowercase character like `lowercase_artist_name-Release_Title-SOURCE-2022-GROUP`, `test.name.2022.S01E01.1080p.WEB.h264-GRP` and other similar naming conventions are not recognized as releases that can be left or right clicked.

Apparently this has been the default behavior forever going back to ~2012 and is still occurring with the latest beta builds, but if it's possible to correct this issue then it would helpful.

**Comment by Sopor** [comment]
This is a known issue ...
