### ISSUE TITLE
How to disable webserver?

### ISSUE THREAD

**Issue by LuzhinSWE** [airdcpp/airdcpp-windows#83]
So I have the issue that Airdc run a webserver as default and I find that strange.
I dont see the point that it should do that by default, it would be better that the user should decide that instead that it runs as default.

So is there any way to disable this webserver permanently?
There is a method to stop it but that I need to do every time I start Airdc which is quite annoying to be frank.

Would be thankful for help!

![Skärmbild 2022-12-20 130511](https://user-images.githubusercontent.com/36010553/208663256-aabdb89d-af63-4859-baa6-6f8977e51c78.jpg)

**Comment by Sopor** [comment]
If you set the port to 0 it should not start the web server `Port (0 = disabled)`, but if you do that you can't run any extensions.

As long as the `Bind address` is set to `Localhost (127.0.0.1)` there is no way that someone can connect through the web server, so i see no reason why the web server can't run even if you don't use it...

**Comment by LuzhinSWE** [comment]
> If you set the port to 0 it should not start the web server `Port (0 = disabled)`, but if you do that you can't run any extensions (that is the reason for the web server to run as default).
> 
> As long as the `Bind address` is set to `Localhost (127.0.0.1)` there is no way that someone outside can connect through the web server, so i see no reason why the web server can't run even if you don't use it...

I have tried to stop it as the picture show and also put the port to 0.
But next time I start Airdc the webserver starts with the default settings.

Maybe so, but I find it strange that Airdc start a server by default that the user is not in control over.
I should be the user that make the active choice to start a server not the program itself.

But maybe the only way to solve this is to stop the server every time I start Airdc?

**Comment by Sopor** [comment]
If you update to 4.12 beta it will not run if you change both ports to 0.

Change update channel to
![image](https://user-images.githubusercontent.com/5789283/209005359-191cc3a4-0087-4a5b-b29e-ab2db0732aab.png)

**Comment by LuzhinSWE** [comment]
> If you update to 4.12 beta it will not run if you change both ports to 0.
> 
> Change update channel to ![image](https://user-images.githubusercontent.com/5789283/209005359-191cc3a4-0087-4a5b-b29e-ab2db0732aab.png) and update from `File / Update check`
> 
> But do keep in mind that the extensions will **NOT** work!

Thanks!
But I prefer stable versions, but then this will be fixed in future updates which is good!

**Comment by maksis** [comment]
https://github.com/airdcpp/airdcpp-windows/commit/4af5feb7fce41e2bfdc27fddfa77d0c0d090ff44
