### ISSUE TITLE
Incorrect user locations & country flags associated with IPs

### ISSUE THREAD

**Issue by ryehamstrawberry** [airdcpp/airdcpp-windows#84]
Incorrect locations and country flags are not being displayed accurately, as I've noticed some US IP addresses are being associated with erroneous countries and flags (example: US IP range being represented as Brazil).

I assume whatever IP database AirDC++ uses to determine user location needs to be updated.

---
AirDC++ v4.11/4.12b

**Comment by Sopor** [comment]
You need to contact `https://db-ip.com`.

This is a free service and it is only updated once every month and it also have reduced coverage and accuracy.

**Comment by ryehamstrawberry** [comment]
For what it's worth, db-ip.com is correctly displaying the correct locations for the IPs in question, but AirDC++ seems not to mirroring them (I assume due to using an old database).

If AirDC++ uses db-ip.com's database, then including the latest IP db in future updates should resolve the disparities I've noticed in recent IPs not matching locations/flags.

**Comment by maksis** [comment]
I've updated the country database on the server. Just delete your current IP database file and restart the client and it will be downloaded.

**Comment by ryehamstrawberry** [comment]
If there a way for you to force clients to update their database files?

Most users will not know how to manually update this file themselves.

**Comment by maksis** [comment]
The client will sync the database automatically every 3 months so there's generally no urgent need for users to update it manually (but it can be done with the steps above if you don't want to wait)

**Comment by ryehamstrawberry** [comment]
Update: I have asked several users to confirm whether or not their countries db has been updated after upgrading to the newest version of AirDC++ v4.20.

It seems users are still utilizing their old countries db even after upgrading.
I'm not sure if this is intentional behavior or not, but I wanted to report it in case the upgrade should have forced an update to the countries db too.

**Comment by maksis** [comment]
The client will sync the database automatically every 3 months regardless of the upgrades

**Comment by ryehamstrawberry** [comment]
> The client will sync the database automatically every 3 months regardless of the upgrades

Thanks! Good work on the update, appreciate your time and effort.
