### ISSUE TITLE
Port forwarded don't same as intented

### ISSUE THREAD

**Issue by k79e** [airdcpp/airdcpp-windows#85]
In settings the port of tcp/udp/tls is port A B C
But in router I don't see ABC forwarded.
It might have port A but port B & C become other numbers.

**Comment by RoLex** [comment]
Could you please provide with a couple of screenshots? One at the client settings where ports are stated, and one in your router settings, where opened ports are stated. It is really hard to understand what you mean. Also it would be nice with some client system logs that say which ports exactly has been forwarder - there is a windows called System log in the client.

**Comment by maksis** [comment]
If you want to use fixed port numbers, you need to disable auto detection and use "Active mode (no router or manual router configuration)"

**Comment by k79e** [comment]
So those manually entered ports are invalid when using automatic connection detect!!
