### ISSUE TITLE
🐛 [Bug]: "Require an exact match" does not actually require an exact match

### ISSUE THREAD

**Issue by Lemm99** [airdcpp/airdcpp-windows#99]
### Prerequisites

- [X] This is not a [support issue or a question](https://github.com/airdcpp/airdcpp-windows/discussions)
- [X] I performed a [cursory search of the issue tracker](https://github.com/airdcpp/airdcpp-windows/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of AirDC++

### Describe the issue

Autosearch -> Search string "test" -> Advanced tab -> Check Require an exact match. Autosearch downloads anything named "test" in any case, like Test, tesT, tEst, etc.

### Expected behavior

When Require an exact match is checked, Autosearch should require an exact match. 

### Actual behavior

When Require an exact match is checked, Autosearch doesn't require an exact match.

### Steps to reproduce the behavior if needed

Autosearch -> Search string "test" -> Advanced tab -> Check Require an exact match. Autosearch downloads anything named "test" in any case, like Test, tesT, tEst, etc.

### AirDC++ version and architecture (x86 or x64)

4.21 x64

### Operating System name, version and architecture

Windows 10 Enterprise 10.0.19045 Build 19045

**Comment by Sopor** [comment]
If you open a search window and search for `test` or `Test`. Do you get different result?

I think you should be able to use `Use a custom matcher for the search results` because it do support regexp.

You can use regexp in a regular search windows and file lists too.

**Comment by Sopor** [comment]
No, Search and AutoSearch do the exact same thing.

Search and Auto search are both case insensitive, but as i explained you could try use `Use a custom matcher for the search results` because it supports RegEx.
